### ISSUE TITLE
Are there facilities in my region not in compliance with their permits right now?

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/ECHO-by-Zip-Code#10]
**What is the question you would like answered?**
Are there facilities in my region not in compliance with their permits right now?

**What information needs to be found in the data in order to answer this question?**
Noncompliance column, date of enforcement data

**Describe what the result should look like:**
Similar to "are there facilities not in compliance in the last 3 years"

**What context can you provide for inclusion in the report? (Or, what context would need to be researched?)**
ECHO registers compliance —that a facility’s emissions are within the limits allowed by its permit(s) — by quarter. Those shown to be exceeding their permitted emissions, either through inspections, evaluations, or monitoring data of various kinds, are considered noncompliant, and in violation. It is worth noting that emissions averaged over a quarter of a year can fail to reflect the level of danger posed by a single and sudden but burst, such as from a massive spill or fire.

**Comment by ericnost** [comment]
I believe this is also now shown?

**Comment by Frijol** [comment]
I don't think so, actually—this is a quibble on "right now". We currently show "in the last 12 qtrs" but not "this qtr". I think there's actually a flag for it in the database.

Not sure if this is a valuable question to ask or not

**Comment by ericnost** [comment]
@Frijol I see! The thing about the "not in compliance in this quarter" flag and the "right now" approach is that it suggests the facility is doing something bad right now, but we don't have that information. Being non-compliant right now/this quarter is the result of doing something in previous months/quarters. I think. I want to say it's more important and informative to provide patterns than "real-time" info.

**Comment by Frijol** [comment]
👍 closing!
