### ISSUE TITLE
Breakdown of noncompliant facilities by permit type

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/ECHO-by-Zip-Code#11]
**What is the question you would like answered?**
What proportion of these non-compliant facilities are violating the Clean Air Act (CAA)?  The Clean Water Act (CWA)? The law for hazardous waste (RCRA)?

**Describe what the result should look like:**
Pie chart

**Comment by ericnost** [comment]
I believe this is now shown in the notebook?

**Comment by Frijol** [comment]
I believe we show a breakdown of the total permits issues, but not isolated to just the noncompliant facilities
