### ISSUE TITLE
Greenhouse gas notebook?

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/ECHO-by-Zip-Code#19]
What is possible? Can get top several, visualize how much that is compared to other things, report/non-report ratio. Maybe that's enough?

**Comment by ericnost** [comment]
Re visualize how much that is compared to other things, I wonder if there is a way to build on this:

http://www.unequalcarbonfootprints.org/ucf/index.cfm

Where you can calculate your own footprint in terms of an average power plant, fertilizer plant etc.

I wonder if there is a good way to visualize facilities against these averages, as well as visualizing individual footprints against facilities (I tried to do this once, actually, but the difference in scale is just so big)

**Comment by Frijol** [comment]
yeah, it's so big it feels meaningless. Maybe we can come up with some very-large comparisons that people could visualize? E.g. "equivalent to X square feet of new forests planted – that's as big as the state of California!" I'm betting there are decent APIs for each of those conversions
