### ISSUE TITLE
A better way to store the data?

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/ECHO-by-Zip-Code#6]
Currently we're using git-lfs (large file storage) to host the ECHO exporter in a raw CSV ([in its own repo](https://github.com/edgi-govdata-archiving/echo-data)) so that CoLab can draw from it.

I'm honestly not sure why it's letting us, it's 1.5x the official permitted free amount of storage.

Right now it's working, but this isn't really a good solution and doesn't scale well to updates (it should update quarterly just for the ECHO Exporter) or potentially adding other data in the future.

(just for completeness, here's the discussion around getting the data in the cloud at all: https://github.com/edgi-govdata-archiving/ECHO-by-Zip-Code/issues/2)

**Comment by ericnost** [comment]
Switched to SBU database
