### ISSUE TITLE
Use database with full history of permits, compliance, enforcement

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/ECHO-by-Zip-Code#7]
Currently, this project pulls the ECHO Exporter CSV *only*,  which is one broad-reaching CSV with only 12 quarters of data.

There has been interest in expanding the history in order to compare between administrations and/or find meaningful trends.

A longer history is available on the [EPA ECHO downloads page](https://echo.epa.gov/tools/data-downloads), but as disparate datasets (RCRA, ICIS, and other alphabet soups are available as separate downloads).

Some investigation is needed for this– my initial questions:

* Is there a good shared column between all of these databases/are they easy to merge?
* How big are the files and where do we keep them (related: https://github.com/edgi-govdata-archiving/ECHO-by-Zip-Code/issues/6)?
* In its current implementation, the notebook runs the rather heavy `.read_csv` function in order to process a zip code, how long will it take if we feed it more data?

**Comment by ericnost** [comment]
Switched to SBU database
