### ISSUE TITLE
Adding user-friendly context into the Notebook

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/ECHO-by-Zip-Code#9]
Likely this should end up split out into a couple of issues to resolve separately, but for now here are some questions I would love for our tool to explain clearly to a user (most of them questions I personally have):

* When is a permit required / what's triggered such that a facility will show up in ECHO?
* What kind of emissions/pollution does our tool *not* show?
* What are all these acronyms? (Especially within RCRA)
* What are the impacts to health & environment that might come from the permit emissions?
* What does "enforcement" look like?
* What is "minor" vs "major emissions in CAA and CWA?
* When does a facility have to report GHG emissions (and why are there so few?)

**Comment by crgreenleaf** [comment]
**When is a permit required / what's triggered such that a facility will show up in ECHO?** 
_Further questions in need of exploring in bulleted lists_

**Facilities regulated by CAA:** "major facilities within the Title V program and synthetic minor facilities that emit or have the potential to emit any pollutant or pollutants at or above 80% of the Title V major facility threshold (SM-80)"

- Title V program?
- synthetic minor facilities
- list out main pollutants included by title v

**Facilities regulated by CWA**: "all categories of dischargers in the National Pollutant Discharge Elimination System (NPDES) program," dischargers are categorized as "majors" and "minors"

- dischargers?
- list out (some?) categories and example in category 
- NPDES program

**Facilities regulated by RCRA**: "all Large Quantity Generators" 
- List out definition/examples of large quantity generators

Side note: It appears that enforcement of different laws varies from state to state in terms of whether it is enforced by the EPA or the state. This would make for an interesting state by state enforcement comparison case-study to determine whether to apply pressure on the state or federal level to achieve maximum enforcement impact.

https://www.epa.gov/compliance/massachusetts-state-review-framework
